### ISSUE TITLE
Clarification on  search API with Request body

### ISSUE THREAD

**Issue by vsk2017** [dadoonet/bano-elastic#2]
just wondering, why the below search API's with Request body are HTTP GET instead of POST ?

https://github.com/dadoonet/bano-elastic/blob/master/script.txt

```
GET banotest/_search
{
  "query": {
    "bool": {
      "filter": {
        "geo_distance": {
          "distance": "1km",
          "location": {
            "lat": 49.09,
            "lon": 1.98
          }
        }
      }
    }
  }
}
```

**Comment by dadoonet** [comment]
Sorry that I did not see your question before 😬 

You can use both GET and POST. I prefer using GET as POST means to me that I want to change something in the server. Here I just want to GET the result of a search request.

See also: https://stackoverflow.com/questions/36939748/elasticsearch-get-request-with-request-body/36940185#36940185
